"""Centralized default values for fossils-vtu2obj."""

from __future__ import annotations

DEFAULT_COLORMAP_NAME = "rainbow"
DEFAULT_N_COLORS = 16
DEFAULT_TEXTURE_HEIGHT = 16
DEFAULT_PREFERRED_SCALAR_FIELD_NAME = "stress_von_mises"

DEFAULT_V_COORD = 0.5

DEFAULT_VOLUME_SHOW_EDGES = False
DEFAULT_VOLUME_SHOW_AXES = True
DEFAULT_VOLUME_EDGE_COLOR = (0.78, 0.80, 0.84)

DEFAULT_BUNDLE_SHOW_EDGES = False
DEFAULT_BUNDLE_SHOW_AXES = True
DEFAULT_BUNDLE_EDGE_COLOR = (0.90, 0.90, 0.92)

DEFAULT_WINDOW_WIDTH = 1600
DEFAULT_WINDOW_HEIGHT = 900
DEFAULT_GUI_SPLITTER_SIZES = (1, 1)

DEFAULT_RENDERER_BACKGROUND = (0.3199969482, 0.3400015259, 0.4299992370)
DEFAULT_TRIHEDRON_VIEWPORT = (0.0, 0.0, 0.20, 0.20)

DEFAULT_EDGE_LINE_WIDTH = 1.8
DEFAULT_EDGE_LINE_OFFSET = (0.0, -8.0)

DEFAULT_SCALAR_BAR_WIDTH = 0.055
DEFAULT_SCALAR_BAR_HEIGHT = 0.78
DEFAULT_SCALAR_BAR_POSITION = (0.92, 0.11)
DEFAULT_SCALAR_BAR_MAXIMUM_WIDTH_PX = 48
DEFAULT_SCALAR_BAR_MAXIMUM_HEIGHT_PX = 360
DEFAULT_SCALAR_BAR_TITLE_FONT_SIZE = 12
DEFAULT_SCALAR_BAR_LABEL_FONT_SIZE = 10
DEFAULT_SCALAR_BAR_LABEL_COUNT = 5

DEFAULT_NORMALS_SPLITTING = True
DEFAULT_NORMALS_FEATURE_ANGLE = 45.0

DEFAULT_SPINBOX_MIN = -1.0e30
DEFAULT_SPINBOX_MAX = 1.0e30
DEFAULT_SPINBOX_DECIMALS = 6
DEFAULT_SPINBOX_STEP = 0.1

DEFAULT_WINDOW_TITLE = "fossils-vtu2obj"
DEFAULT_GITHUB_URL = "https://github.com/rboman/vtu2obj"
