"""Centralized default values for fossils-vtu2obj."""

from __future__ import annotations

DEFAULT_COLORMAP_NAME = "rainbow"
DEFAULT_N_COLORS = 16
DEFAULT_N_COLORS_MIN = 2
DEFAULT_N_COLORS_MAX = 4096
DEFAULT_TEXTURE_HEIGHT = 16
DEFAULT_PREFERRED_SCALAR_FIELD_NAME = "stress_von_mises"
DEFAULT_GENERATE_NORMALS = True

DEFAULT_V_COORD = 0.5

DEFAULT_VOLUME_SHOW_EDGES = False
DEFAULT_VOLUME_SHOW_AXES = True
DEFAULT_VOLUME_SHOW_BOUNDING_BOX = False
DEFAULT_VOLUME_EDGE_COLOR = (0.78, 0.80, 0.84)

DEFAULT_BUNDLE_SHOW_EDGES = False
DEFAULT_BUNDLE_SHOW_AXES = True
DEFAULT_BUNDLE_SHOW_BOUNDING_BOX = False
DEFAULT_BUNDLE_EDGE_COLOR = (0.90, 0.90, 0.92)

DEFAULT_BACKGROUND_PRESET = "current_solid"
DEFAULT_LIGHTING_PRESET = "studio_soft"
DEFAULT_LIGHTING_INTENSITY = 100
DEFAULT_CAMERA_PRESET = "3d_angled"

BACKGROUND_PRESET_NAMES = (
    "current_solid",
    "paraview_dark_gradient",
    "black",
    "white",
)
LIGHTING_PRESET_NAMES = (
    "flat",
    "studio_soft",
    "studio_contrast",
)
CAMERA_PRESET_NAMES = (
    "3d_angled",
    "+X",
    "-X",
    "+Y",
    "-Y",
    "+Z",
    "-Z",
)

BACKGROUND_PRESET_LABELS = {
    "current_solid": "Current solid",
    "paraview_dark_gradient": "ParaView dark gradient",
    "black": "Black",
    "white": "White",
}
LIGHTING_PRESET_LABELS = {
    "flat": "Flat",
    "studio_soft": "Studio soft",
    "studio_contrast": "Studio contrast",
}
CAMERA_PRESET_LABELS = {
    "3d_angled": "3D angled",
    "+X": "+X",
    "-X": "-X",
    "+Y": "+Y",
    "-Y": "-Y",
    "+Z": "+Z",
    "-Z": "-Z",
}

DEFAULT_WINDOW_WIDTH = 1600
DEFAULT_WINDOW_HEIGHT = 900
DEFAULT_GUI_SPLITTER_SIZES = (1, 1)
DEFAULT_PREVIEW_WINDOW_SIZE = (1280, 800)

DEFAULT_RENDERER_BACKGROUND = (0.3199969482, 0.3400015259, 0.4299992370)
DEFAULT_RENDERER_BACKGROUND_2 = (0.3199969482, 0.3400015259, 0.4299992370)
PARAVIEW_DARK_GRADIENT_BACKGROUND = (0.22, 0.24, 0.30)
PARAVIEW_DARK_GRADIENT_BACKGROUND_2 = (0.06, 0.07, 0.10)
DEFAULT_TRIHEDRON_VIEWPORT = (0.0, 0.0, 0.20, 0.20)
DEFAULT_TEXTURE_PREVIEW_SIZE = (260, 96)

DEFAULT_EDGE_LINE_WIDTH = 1.8
DEFAULT_EDGE_LINE_OFFSET = (0.0, -8.0)

DEFAULT_SCALAR_BAR_WIDTH = 0.055
DEFAULT_SCALAR_BAR_HEIGHT = 0.78
DEFAULT_SCALAR_BAR_POSITION = (0.92, 0.11)
DEFAULT_SCALAR_BAR_MAXIMUM_WIDTH_PX = 48
DEFAULT_SCALAR_BAR_MAXIMUM_HEIGHT_PX = 360
DEFAULT_SCALAR_BAR_TITLE_FONT_SIZE = 12
DEFAULT_SCALAR_BAR_LABEL_FONT_SIZE = 10
DEFAULT_SCALAR_BAR_LABEL_COUNT = 5

DEFAULT_NORMALS_SPLITTING = True
DEFAULT_NORMALS_FEATURE_ANGLE = 45.0

DEFAULT_SPINBOX_MIN = -1.0e30
DEFAULT_SPINBOX_MAX = 1.0e30
DEFAULT_SPINBOX_DECIMALS = 6
DEFAULT_SPINBOX_STEP = 0.1

DEFAULT_WINDOW_TITLE = "fossils-vtu2obj"
DEFAULT_GITHUB_URL = "https://github.com/rboman/vtu2obj"
